url: https://bluebattleship.github.io/
baseurl: 

# Site settings
title: Blue Battleship
email: contact@bluebattleship.com
description: "Development done right."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 007bb7
  secondary: 0592d4
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Cobus Bernard
  pic: 1
  position: Problem Solver
  social:
    - title: twitter
      url: http://twitter.com/cobusbernard#
    - title: github
      url: http://github.com/cobusbernard
    - title: stack-overflow
      url: http://stackoverflow.com/users/1278297/cobus-bernard

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/bluebattleship
  - title: github
    url: http://github.com/bluebattleship

# Postal address (add as many lines as necessary)
address:
  - line: 5 Stanford Road, Rondebosch, 7700
  - line: Cape Town, South Africa

# Build settings
markdown: kramdown
permalink: pretty
